%% Proyecto Final TEC, Paulo Granados
clc, clear all

% Noticias
deportes_i = {'http://www.emol.com/noticias/Deportes/2018/06/14/909831/En-vivo-La-Roja-se-juega-la-clasificacion-al-Mundial-Sub-19-de-basquetbol-ante-Puerto-Rico.html'...
    'http://www.emol.com/noticias/Deportes/2018/06/14/909838/Rusia-le-pasa-una-aplanadora-a-la-Arabia-de-Pizzi-y-la-golea-50-en-el-inicio-del-Mundial.html'...
    'http://www.emol.com/noticias/Deportes/2018/06/14/909804/Mira-el-desafortunado-golpe-con-el-que-Jordan-Spieth-hizo-un-triple-bogey-en-el-comienzo-del-US-Open.html'...
    'http://www.emol.com/noticias/Deportes/2018/06/14/909786/Rueda-habla-de-dolor-amargura-y-nostalgia-por-la-ausencia-de-Chile-en-el-Mundial.html'...
    'http://www.emol.com/noticias/Deportes/2018/06/14/909775/Garin-remonta-un-sufrido-partido-y-se-instala-en-cuartos-del-Challenger-de-Lyon.html'...
    'http://www.emol.com/noticias/Deportes/2018/06/13/909667/Federer-sufre-para-ganar-en-su-regreso-a-las-canchas-y-sigue-en-carrera-para-desbancar-a-Nadal-del-1-del-mundo.html'...
    'http://www.emol.com/noticias/Deportes/2018/06/12/909506/Como-inmediatamente-en-su-regreso-Federer-podria-desplazar-esta-semana-a-Nadal-del-1-del-mundo.html'...
    'http://www.emol.com/noticias/Deportes/2018/06/10/909310/Sebastien-Vettel-fue-el-mas-veloz-de-principio-a-fin-gana-el-GP-de-Canada-y-recupera-el-liderato-de-la-F1.html'...
    'http://www.emol.com/noticias/Deportes/2018/05/27/907641/F1-Daniel-Ricciardo-cierra-un-fin-de-semana-redondo-y-se-adjudica-el-Gran-Premio-de-Monaco.html'...
    'http://www.emol.com/noticias/Deportes/2018/05/13/906002/Formula-Uno-Hamilton-suma-su-segunda-victoria-de-la-temporada-tras-quedarse-con-el-Gran-Premio-de-Espana.html'...
    'http://www.ahoranoticias.cl/noticias/deportes/227452-marcelo-bielsa-es-confirmado-como-el-nuevo-entrenador-del-leeds-de-inglaterra.html'...
    'http://www.ahoranoticias.cl/noticias/deportes/227414-antoine-griezmann-se-queda-en-el-atletico-madrid.html'...
    'http://www.ahoranoticias.cl/noticias/deportes/227395-entre-lagrimas-julen-lopetegui-fue-presentado-como-nuevo-entrenador-del-real-madrid.html'...
    'http://www.ahoranoticias.cl/noticias/deportes/227272-pumas-de-mexico-anuncia-el-fichaje-del-ariete-chileno-felipe-mora.html'...
    'http://www.ahoranoticias.cl/noticias/deportes/227210-west-ham-cumple-con-una-de-las-principales-exigencias-puestas-por-manuel-pellegrini-en-su-llegada-al-club.html'...
    'http://www.marca.com/motor/24-horas-le-mans/2018/06/17/5b25a1ffe5fdea47678b4646.html'...
    'http://www.marca.com/motor/motogp/gp-italia/2018/06/03/5b1459d6468aeb516e8b458e.html'...
    'http://www.marca.com/baloncesto/nba/2018/06/16/5b24b9fb268e3e6e6d8b464d.html'... 
    'http://www.marca.com/apuestas-deportivas/2018/06/16/5b2546d146163f09088b4671.html'...
    
     };
 
 deportes_n = {'http://www.adnradio.cl/noticias/deportes/gustavo-canales-fue-un%C2%A0honor-vestir-estas-dos-camisetas-no-los-olvidare-nunca/20180615/nota/3762704.aspx'...
    'http://www.adnradio.cl/noticias/deportes/esta-es-la-probable-formacion-de-la-u-para-recibir-a-la-serena-por-copa-chile/20180615/nota/3762559.aspx'...
    'http://www.emol.com/noticias/Deportes/2018/06/15/910028/Emocionado-hasta-las-lagrimas-y-con-companeros-de-la-U-campeona-de-la-Sudamericana-y-de-la-Union-Canales-tuvo-su-partido-de-despedida.html'...
    'http://www.emol.com/noticias/Deportes/2018/05/29/907843/Los-importantes-torneos-que-jugara-Jarry-previos-a-Wimbledon-y-que-serian-clave-para-no-descender-mucho-en-el-ranking.html'...
    'http://www.radiovalparaiso.cl/2018/05/08/mas-de-200-deportistas-participaran-en-la-4ta-copa-altomonte-de-hockey-cesped/'...   
    'http://www.emol.com/noticias/Deportes/2018/06/12/909620/Delegacion-chilena-recibio-reconocimiento-en-La-Moneda-por-su-destacada-participacion-en-los-Juegos-Odesur.html'...
    'http://www.emol.com/noticias/Deportes/2018/06/13/909733/Espina-esta-feliz-de-volver-a-Colo-Colo-su-segunda-casa-y-ya-hablo-de-su-politica-para-fichajes.html'...
    'http://www.emol.com/noticias/Deportes/2018/06/11/909477/Marcelo-Espina-le-gana-la-pulseada-a-Sebastian-Gonzalez-y-es-elegido-como-el-nuevo-gerente-deportivo-de-Colo-Colo.html'...
    'http://www.emol.com/noticias/Deportes/2018/06/10/909324/Cinco-equipos-de-la-B-y-uno-de-Segunda-Division-dieron-la-sorpresa-en-el-inicio-de-la-segunda-ronda-de-Copa-Chile.html'...
    'http://www.emol.com/noticias/Deportes/2018/06/10/909322/Tres-atacantes-juego-por-las-bandas-y-transiciones-rapidas-Como-jugo-la-U-en-el-primer-partido-de-Kudelka.html'...
    'http://www.soychile.cl/San-Antonio/Deportes/2018/06/16/539606/Estos-serian-los-11-guerreros-de-San-Antonio-Unido-que-enfrentaran-hoy-al-puntero-de-la-Segunda-Division.aspx'...
    'http://www.latercera.com/el-deportivo/noticia/la-u-se-instala-autoridad-los-octavos-la-copa-chile/209415/'...
    
    
    
    };
 
deportes_l = {'http://www.soychile.cl/Valparaiso/Deportes/2018/06/15/539587/Everton-pierde-en-penales-ante-Cobresal-en-Vina-del-Mar-y-queda-eliminado-de-Copa-Chile.aspx'...
     'http://www.radiovalparaiso.cl/2018/05/11/con-exito-finalizo-torneo-de-tenis-otono-2018-en-el-club-toesca-de-valparaiso/'...
     'http://www.radiovalparaiso.cl/2018/03/19/comunicado-oficial-nicolas-cordova-no-seguira-como-tecnico-de-santiago-wanderers/'...
     
     
 };

economia_i = { 'http://www.elmundo.es/economia/macroeconomia/2018/06/15/5b23b022e2704ec41a8b4820.html'...
  'http://www.elmundo.es/economia/2018/06/15/5b23e74422601da81a8b45b0.html'...
  'http://www.elmundo.es/economia/empresas/2018/06/15/5b23afe5e5fdeac1548b46b4.html'...
  'http://www.elmundo.es/madrid/2018/06/13/5b21098f468aebdd558b45cd.html'...
  'http://www.elmundo.es/comunidad-valenciana/2018/06/13/5b20c7a8e2704e79378b464c.html'...
  'http://www.elmundo.es/economia/macroeconomia/2018/06/13/5b20c1f7268e3e8b3b8b45aa.html'...
  'http://www.elmundo.es/comunidad-valenciana/2018/06/12/5b1f932c46163f734e8b4646.html'...
  'http://www.elmundo.es/economia/macroeconomia/2018/05/31/5b0fbb22ca474136578b457a.html'...
  'http://www.elmundo.es/economia/2018/05/12/5af5daba22601d9b678b45b9.html'...
  'http://www.elmundo.es/economia/macroeconomia/2018/05/22/5b03f89546163f913a8b460d.html'...
  'http://www.abc.es/economia/abci-empeora-prevision-crecimiento-espana-este-crisis-catalana-201801221459_noticia.html'...
  'http://www.emol.com/noticias/Economia/2018/06/16/910071/China-responde-a-Trump-y-sube-impuestos-a-la-soya-autos-electricos-y-el-whiskey-de-EEUU.html'...
  
};

economia_n = {'http://www.emol.com/noticias/Economia/2018/06/15/910017/Gobierno-expresa-molestia-por-la-forma-que-se-despidio-a-1209-trabajadores-en-San-Antonio.html'...
     'http://www.24horas.cl/economia/banco-de-chile-debera-pagar-us-30-millones-a-sus-clientes-tras-cobros-indebidos-en-linea-de-sobregiro-pactado-2741208'...
     'http://www.24horas.cl/economia/parafina-registrara-fuerte-baja-y-las-bencinas-subiran-por-octava-semana-consecutiva-2739505'...
     'http://www.24horas.cl/economia/banco-central-sube-proyeccion-de-crecimiento-economico-entre-un-325-y-4-2739899'...
     'http://www.24horas.cl/economia/fiscalia-nacional-economica-anuncia-investigacion-por-compra-del-24-de-sqm-por-parte-de-tianqi-2741434'...
    'http://www.t13.cl/noticia/negocios/ipom-banco-central-mejora-expectativas-crecimiento-2018-informe-junio'...
    'http://www.ahoranoticias.cl/noticias/economia/225477-hacienda-se-reune-por-tercera-vez-con-pinera-por-reforma-tributaria.html'...
    'http://www.ahoranoticias.cl/noticias/economia/225475-ipsa-repunta-por-buenas-utilidades-de-copec-enel-y-latam-airlines.html'...
    'http://www.ahoranoticias.cl/noticias/economia/224604-banco-central-economia-chilena-crece-un-42-durante-el-primer-trimestre.html'...
    'http://www.ahoranoticias.cl/noticias/economia/224345-gobierno-deja-fuera-al-sector-publico-en-reduccion-de-plazo-de-pago-a-pymes.html'...
    'http://www.emol.com/noticias/Economia/2018/06/17/910129/Marcel-tras-IPoM-No-hay-que-precipitar-decisiones-que-puedan-poner-en-riesgo-la-normalizacion-de-la-economia.html'...
    
 };

economia_l = {'http://www.noticias.usm.cl/2018/04/05/sansano-asume-como-seremi-de-economia-de-la-region-de-valparaiso/'...
    'http://www.t13.cl/noticia/negocios/la-campana-busca-recuperar-mercado-cruceros-valparaiso'...
    
};

espectaculo_i = {'http://www.emol.com/noticias/Espectaculos/2018/06/15/909948/Fallece-ex-integrante-de-Locomia-a-los-46-anos.html'...
    'http://www.emol.com/noticias/Espectaculos/2018/06/15/909937/Directo-desde-el-Teatro-Municipal-Opera-El-Cristo-de-Elqui-sera-transmitida-de-forma-gratuita-via-streaming.html'...
    'http://www.emol.com/noticias/Espectaculos/2018/06/13/909752/Ricky-Martin-asegura-que-le-encantaria-poder-volver-a-salir-del-closet-y-que-sus-hijos-fueran-homosexuales.html'...
    'http://www.emol.com/noticias/Espectaculos/2018/06/13/909645/Kelly-McGill-estrella-de-Top-Gun-sorprende-con-irreconocible-aspecto-a-32-anos-del-lanzamiento-del-filme.html'...
    'http://www.emol.com/noticias/Espectaculos/2018/06/14/909860/Robbie-Williams-desata-la-polemica-tras-hacer-un-gesto-obsceno-durante-inauguracion-del-Mundial.html'...
    'http://www.emol.com/noticias/Espectaculos/2018/06/15/910012/Concierto-de-rapero-musulman-en-el-Bataclan-genera-polemica-en-Francia.html'...
    'http://www.emol.com/noticias/Espectaculos/2018/06/15/909979/Gilberto-Santa-Rosa-volvera-a-Chile-para-presentarse-en-tres-ciudades-del-pais.html'...
    'http://www.emol.com/noticias/Espectaculos/2018/06/15/909937/Directo-desde-el-Teatro-Municipal-Opera-El-Cristo-de-Elqui-sera-transmitida-de-forma-gratuita-via-streaming.html'...
    'http://www.abc.es/espana/casa-real/abci-premios-princesa-mantienen-gerona-pese-intento-boicot-separatista-201806160230_noticia.html'... 
    'http://www.emol.com/noticias/Espectaculos/2018/06/17/910019/Paulina-Garcia-y-su-nuevo-trabajo-internacional-en-Matar-al-padre.html'...
    'http://www.emol.com/noticias/Espectaculos/2018/06/16/910096/Joaquin-Sabina-se-queda--totalmente-mudo-en-mitad-de-concierto-en-Madrid.html'...
    
    
    };

espectaculo_n = {'http://www.24horas.cl/tendencias/espectaculosycultura/rojo-lidera-la-sintonia-con-eliminacion-de-ronald-perez-y-tatiana-fernandez-y-deja-a-mega-en-tercer-lugar-2741843'...
    'http://www.24horas.cl/tendencias/espectaculosycultura/rojo-el-emocionante-reencuentro-de-hernan-y-juan-angel-con-sus-padres-2741602'...
    'http://www.chvnoticias.cl/espectaculos/tengo-pena-el-lamentable-hecho-que-le-ocurrio-a-denise-rosenthal/2018-06-14/150253.html'...
    'http://www.chvnoticias.cl/espectaculos/yo-soy-americo-libro-del-cantante-relata-su-desconocida-historia/2018-06-13/153641.html'...
    'http://www.chvnoticias.cl/espectaculos/el-flaco-la-confesion-de-paul-vazquez-en-la-divina-comida/2018-06-12/215336.html'...
    'http://www.soychile.cl/Calama/Sociedad/2018/06/15/539381/Profesora-calamena-gano-el-programa-Vertigo.aspx?utm_source=facebook&utm_medium=[Francisca]&utm_campaign=Fanpage'...
    'http://www.emol.com/noticias/Espectaculos/2018/06/16/909993/Director-de-Cada-dia-el-filme-que-aborda-la-pansexualidad-Trata-sobre-enamorarse-de-la-esencia-de-una-persona.html'...
    'http://www.emol.com/noticias/Espectaculos/2018/06/15/909979/Gilberto-Santa-Rosa-volvera-a-Chile-para-presentarse-en-tres-ciudades-del-pais.html'...
    'http://www.emol.com/noticias/Espectaculos/2018/06/17/910158/Los-Increibles-2-debuta-con-record-en-taquilla-norteamericana-y-alcanza-en-ventas-la-mayor-cifra-de-la-historia-en-un-film-de-animacion.html'...
    'http://www.emol.com/noticias/Espectaculos/2018/06/17/910007/Autor-de-biografia-de-Americo-repasa-la-relacion-del-cantante-con-su-padre-Es-muy-tentador-verlo-como-Luisito-Rey.html'...
    'http://www.emol.com/noticias/Espectaculos/2018/06/16/909993/Director-de-Cada-dia-el-filme-que-aborda-la-pansexualidad-Trata-sobre-enamorarse-de-la-esencia-de-una-persona.html'...
    'http://www.emol.com/noticias/Espectaculos/2018/06/16/909997/De-las-baladas-y-el-pop-al-reggaeton-Conoce-a-los-artistas-que-se-atrevieron-a-incursionar-en-la-musica-urbana.html'...
    'http://www.emol.com/noticias/Espectaculos/2018/06/15/909937/Directo-desde-el-Teatro-Municipal-Opera-El-Cristo-de-Elqui-sera-transmitida-de-forma-gratuita-via-streaming.html'...
    'http://www.emol.com/noticias/Espectaculos/2018/06/13/909697/Paso-cuatro-horas-al-dia-en-Internet-y-una-con-mis-papas-La-realidad-de-los-centennials-o-nativos-digitales-se-visibiliza-en-el-teatro.html'...
    
    
    };

espectaculo_l = {'http://www.ahoranoticias.cl/noticias/tendencias/191265-galeria-revisa-las-mejores-fotos-del-sencillo-piscinazo-de-kika-silva.html'...
    'http://www.soychile.cl/Valparaiso/Cultura/2016/06/02/397182/Hoy-se-inicia-la-6ta-version-de-los-Temporales-Musicales-en-Valparaiso.aspx'...
    'http://www.t13.cl/blog/columnas-juan-manuel-vial/otra-cosa-es-tambor'...
    
};


policial_i = { 'http://www.eltiempo.com/mundo/eeuu-y-canada/hombre-armado-esta-atrincherado-en-panama-city-miami-220806'...
  'http://www.eltiempo.com/mundo/eeuu-y-canada/autor-del-tiroteo-en-colegio-de-texas-219470'...
  'http://www.eltiempo.com/mundo/eeuu-y-canada/nikolas-cruz-quiere-donar-su-herencia-a-victimas-de-tiroteo-en-parkland-florida-204206'...
  'http://www.eltiempo.com/mundo/eeuu-y-canada/tiroteo-en-escuela-de-santa-fe-texas-estados-unidos-219070'...
  'http://www.eltiempo.com/mundo/eeuu-y-canada/tiroteo-en-un-restaurante-en-nashville-ee-uu-208166'...
  'http://www.europapress.es/asturias/noticia-tres-fallecidos-colision-coche-camion-san-tirso-abres-20180615180130.html'...
  'http://www.europapress.es/nacional/noticia-fuerzas-seguridad-apoyan-retirar-concertinas-piden-otros-elementos-disuasion-alertan-efecto-llamada-20180615162915.html'...
  'http://www.europapress.es/castilla-y-leon/noticia-desarticulado-grupo-responsable-43-robos-casas-salamanca-valladolid-leon-cordoba-pontevedra-20180615162154.html'...
  'http://www.elmundo.es/espana/2018/04/06/5ac73963e2704e96118b4605.html'...
  'http://www.notimerica.com/sociedad/noticia-policia-espanola-detiene-brasil-fugitivo-espanol-buscado-asesinato-2008-abogado-20171016171725.html'...
  'http://www.elmostrador.cl/noticias/mundo/2018/03/16/la-conmocion-que-causa-en-brasil-el-asesinato-de-la-popular-concejala-de-izquierda-de-rio-de-janeiro-marielle-franco/'...
  'http://www.rtve.es/noticias/20180315/conmocion-brasil-tras-asesinato-balazos-concejal-activista-marielle-franco/1697783.shtml'...
  'http://www.abc.es/internacional/abci-mueren-17-personas-fiesta-curso-caracas-tras-estallar-bomba-gases-lacrimogenos-201806161714_noticia.html'... 
  };

policial_n = { 'http://www.lacuarta.com/noticia/femicidio-crimen-mensajes-facebook/'...
  'http://www.lacuarta.com/noticia/chileno-mato-emparedo-pareja/'...
  'http://www.lacuarta.com/noticia/informativo-pm-confeso-doble-crimen-maipu-fue-formalizado-violacion-homicidio/'...
  'http://www.lacuarta.com/noticia/capturan-delincuentes-cuento-tio-nana/'...
  'http://www.lacuarta.com/noticia/presidente-fech-acoso-laboral/'...
  'http://www.lacuarta.com/noticia/sebastian-pinera-realizo-ronda-extraordinaria-la-pintana/'...
  'http://www.lacuarta.com/noticia/partearon-instalar-urinario-calle/'...
  'http://www.lacuarta.com/noticia/atropellar-carabinero-chofer-uber/'...
  'http://www.lacuarta.com/noticia/detalles-doble-homicidio-maipu/'...
  'http://www.soychile.cl/Santiago/Policial/2018/06/15/539467/Formalizan-a-joven-que-mato-a-su-ex-polola-y-a-la-madre-de-ella-en-Maipu.aspx'...
  'http://www.soychile.cl/Santiago/Policial/2018/06/15/539408/Formalizaran-a-hombre-que-mato-a-su-pareja-en-Penalolen.aspx'...
  'http://www.soychile.cl/Santiago/Policial/2018/06/15/539376/Juez-dejo-libre-a-imputado-que-participo-en-un-alunizaje-porque-delito-ocurrio-en-la-Tierra.aspx'...
  'http://www.soychile.cl/Santiago/Policial/2018/06/14/539368/Detuvieron-a-hombre-acusado-de-violar-a-su-cunada-con-discapacidad-mental.aspx'...
  'http://www.soychile.cl/Santiago/Policial/2018/06/14/539238/En-prision-preventiva-quedo-joven-que-mato-con-una-llave-de-cruz-a-cliente-en-San-Ramon.aspx'...
  'http://www.soychile.cl/Santiago/Policial/2018/06/08/538207/Pelea-entre-dos-escolares-termino-con-un-adulto-agredido-en-Maipu.aspx'...
  'http://www.soychile.cl/Calama/Sociedad/2018/06/16/539695/Cambio-de-mando-en-la-Comisaria-de-Carabineros-de-Calama.aspx'...
  
  
  };

policial_l = { 'http://www.soychile.cl/Valparaiso/Policial/2018/06/15/539465/Accidente-en-el-camino-La-Polvora-de-Valparaiso-dejo-una-persona-herida.aspx'...
  'http://www.soychile.cl/Valparaiso/Sociedad/2018/06/14/539230/12-anos-de-carcel-a-hombre-que-mato-a-golpes-a-su-hijo-de-4-meses-en-Valparaiso.aspx'...
  'http://www.soychile.cl/Valparaiso/Policial/2018/06/14/539210/Desbaratan-punto-de-venta-de-droga-en-la-villa-Nueva-Costanera-de-Casablanca.aspx'...
  'http://www.soychile.cl/Valparaiso/Policial/2018/06/13/538950/Femicidio-frustrado-en-Vina-hombre-ataco-con-cuchillo-a-expareja-en-pleno-centro.aspx'...
  'http://www.soychile.cl/Valparaiso/Policial/2018/06/08/538131/La-PDI-indaga-el-asesinato-de-un-hombre-de-37-anos-en-la-poblacion-Joaquin-Edwards-Bello.aspx'...
  'http://www.t13.cl/noticia/nacional/valparaiso-detienen-banda-transportaba-cocaina-ambulancia'...
  'http://www.t13.cl/noticia/nacional/valparaiso-tribunal-quita-custodia-tios-bebe-denuncia-abuso-sexual'...
  'http://www.t13.cl/noticia/nacional/mujer-es-acusada-matar-golpes-su-nieto-7-anos'...
  'http://www.t13.cl/noticia/nacional/chofer-del-bus-volcado-valparaiso-queda-reclusion-nocturna'...
  'http://www.t13.cl/noticia/nacional/briganti-es-declarado-culpable-muertes-dos-estudiantes-marcha-valparaiso'...
  'http://www.t13.cl/noticia/nacional/os7-carabineros-desarticulo-banda-era-operada-carcel-valparaiso'...
  'http://www.t13.cl/noticia/nacional/joven-embarazada-es-baleada-cabeza-olmue'...
  
  };


politica_i = { 'http://www.abc.es/espana/abci-fernando-valenzuela-y-juan-pablo-laiglesia-nuevos-secretarios-estado-exteriores-iberoamerica-201806150439_noticia.html'...
    'http://www.abc.es/internacional/abci-gobierno-venezolano-libera-39-opositores-como-acto-reconciliacion-201806021100_video.html'...
    'http://www.abc.es/internacional/abci-merkel-gana-pasapalabra-parlamentario-201806070235_noticia.html'...
    'http://www.abc.es/espana/abci-cuatro-anos-reinado-plagado-dias-historicos-201806030600_noticia.html'...
    'http://www.abc.es/internacional/abci-presidente-italia-encarga-giuseppe-conte-formar-gobierno-201805231928_noticia.html'...
    'http://www.abc.es/internacional/abci-nicolas-maduro-elecciones-voto-decide-votos-o-balas-patria-o-colonia-o-violencia-201805201514_noticia.html'...
    'http://www.abc.es/internacional/abci-gobierno-malasia-pierde-poder-tras-seis-decadas-hegemonia-201805101855_noticia.html'...
    'http://www.abc.es/economia/abci-iata-cerrara-oficina-caracas-partir-enero-inestabilidad-politica-201712051224_noticia.html'...
    'http://www.abc.es/internacional/abci-estados-unidos-tacha-narcoestado-violento-venezuela-201711132250_noticia.html'...
    'http://www.abc.es/espana/abci-prensa-internacional-habla-espana-limite-201710281204_noticia.html'...
    'http://www.abc.es/espana/catalunya/abci-embajadas-nacionalistas-dispendio-avalado-tribunal-constitucional-201710251858_noticia.html'...
    'http://www.abc.es/espana/abci-diputado-avila-jose-ramon-garcia-hernandez-anuncia-candidatura-congreso-pp-201806161509_noticia.html'...
    
};

politica_n = {'http://www.radiovalparaiso.cl/2018/05/28/sebastian-pinera-sube-su-aprobacion-en-encuesta-cadem/'...
    'http://www.radiovalparaiso.cl/2018/05/21/declaracion-del-gobierno-de-chile-respecto-del-proceso-electoral-en-venezuela/'...
    'http://www.radiovalparaiso.cl/2018/05/17/senador-ossandon-recuerda-errores-de-gobierno-anterior-a-ver-si-a-los-guardianes-de-las-arcas-fiscales-les-da-un-poquito-de-pudor/'...
    'http://www.radiovalparaiso.cl/2018/05/16/senador-lagos-weber-cuestiona-postergacion-de-nombramiento-de-nuevo-embajador-chileno-en-ese-pais/'...
    'http://www.radiovalparaiso.cl/2018/05/03/senador-lagos-weber-critico-dichos-del-titular-de-hacienda-en-polemica-por-eventual-deficit-de-5-mil-500-millones-de-dolares/'...
    'http://www.radiovalparaiso.cl/2018/04/24/senador-lagos-weber-y-propuesta-de-modificacion-a-la-reforma-tributaria-no-creo-que-la-reforma-tributaria-sea-un-obstaculo-al-crecimiento-economico-de-chile/'...
    'http://www.radiovalparaiso.cl/2018/04/24/diputada-camila-flores-pidio-a-ministro-de-justicia-endurecer-penas-de-delitos/'...
    'http://www.radiovalparaiso.cl/2018/04/23/senador-lagos-weber-y-diputado-mirosevic-presentaron-proyecto-de-eutanasia-en-chile/'...
    'http://www.radiovalparaiso.cl/2018/04/20/diputado-andres-celis-no-hay-financiamiento-para-proyecto-compensatorio-a-victimas-de-dd-hh/'...
    'http://www.radiovalparaiso.cl/2018/04/19/abrupta-y-polemica-suspension-de-sesion-de-la-camara-de-diputados-tras-dichos-de-parlamentario-sobre-victimas-de-la-dictadura/'...
    'http://www.radiovalparaiso.cl/2018/04/16/diputado-pardo-y-ampliacion-de-gratuidad-en-cft-e-ip-hace-justicia-con-los-sectores-mas-postergados-en-educacion/'...
    'http://www.t13.cl/noticia/politica/jorge-sharp-liderazgos-del-fa-no-han-estado-altura'...
    
};

politica_l = {'http://www.soychile.cl/Valparaiso/Politica/2017/06/23/471808/Senador-Lagos-Weber-seria-dado-de-alta-manana-debera-reposar-por-30-dias.aspx'...
    'http://www.radiovalparaiso.cl/2018/05/14/diputado-torres-dc-pide-agilizar-envio-de-ley-de-puertos-y-respalda-propuesta-de-alcalde-sharp/'...
    'http://www.radiovalparaiso.cl/2018/04/19/consejero-regional-percy-marin-rn-es-el-nuevo-presidente-del-core-de-valparaiso/'...
    'http://www.t13.cl/radio/politica/mesa-central/noticia/sharp-reitero-criticas-centralismo-capitalino-cuenta-publica-pinera'...
    
    };
% Noticias por categoria
deportes = [deportes_i deportes_n deportes_l];
economia = [economia_i economia_n economia_l];
espectaculo = [espectaculo_i espectaculo_n espectaculo_l];
policial = [policial_i policial_n policial_l];
politica = [politica_i politica_n politica_l];

% Se etiquetan las noticias de acuerdo a su categoria
Categoria_tipo = {};
for i = 1:length(deportes)
    Categoria_tipo{end + 1} = 'Deportes';
end
for i = 1:length(economia)
    Categoria_tipo{end + 1} = 'Economia';
end
for i = 1:length(espectaculo)
    Categoria_tipo{end + 1} = 'Espectaculo';
end
for i = 1:length(policial)
    Categoria_tipo{end + 1} = 'Policial';
end
for i = 1:length(politica)
    Categoria_tipo{end + 1} = 'Politica';
end

% Se llama a la funcion extraer_palabras_importantes, la cual retorna las
% palabras con mayor frecuencia (50 palabras por categoria)
palabras_deportes = extraer_palabras_importantes(deportes)
palabras_economia = extraer_palabras_importantes(economia)
palabras_politica = extraer_palabras_importantes(politica)
palabras_policial = extraer_palabras_importantes(policial)
palabras_espectaculo = extraer_palabras_importantes(espectaculo)

% Se juntan las palabras importantes en un solo vector
palabras_tipo = [palabras_deportes...
            palabras_economia... 
            palabras_espectaculo...
            palabras_policial... 
            palabras_politica]

% Se eliminan los espacios en blanco
palabras_tipo_final = [palabras_tipo(1:50) palabras_tipo(52:101)...
                       palabras_tipo(103:152) palabras_tipo(154:203)...
                       palabras_tipo(205:252)]

% Guardamos las palabras
save palabras_tipo_final.mat palabras_tipo_final

                   
% Se etiquetan las noticias de acuerdo al lugar
local = [deportes_l economia_l espectaculo_l policial_l politica_l]
nacional = [deportes_n economia_n espectaculo_n policial_n politica_n]
internacional = [deportes_i economia_i espectaculo_i policial_i politica_i]        
        
Categoria_lugar = {};
for i = 1:length(local)
    Categoria_lugar{end + 1} = 'Local';
end
for i = 1:length(nacional)
    Categoria_lugar{end + 1} = 'Nacional';
end
for i = 1:length(internacional)
    Categoria_lugar{end + 1} = 'Internacional';
end

% Mismo procedimiento
palabras_local = extraer_palabras_importantes(local)
palabras_nacional = extraer_palabras_importantes(nacional)
palabras_internacional = extraer_palabras_importantes(internacional)

% Mismo procedimiento
palabras_lugar = [palabras_local palabras_nacional palabras_internacional]
palabras_lugar_final = [palabras_lugar(1:49) palabras_lugar(51)...
                        palabras_lugar(52:101) palabras_lugar(103:152)]

save palabras_lugar_final.mat palabras_lugar_final

% Se juntan todas las noticias para la confeccion de la matriz A_tipo de
% ocurrencias
noticias = [deportes_i deportes_n deportes_l economia_i economia_n economia_l...
    espectaculo_i espectaculo_n espectaculo_l policial_i policial_n policial_l...
    politica_i politica_n politica_l];

% Mismo procedimiento, pero para la matriz A_lugar
noticias_lugar = [deportes_l economia_l espectaculo_l policial_l politica_l...
                  deportes_n economia_n espectaculo_n policial_n politica_n...
                  deportes_i economia_i espectaculo_i policial_i politica_i] 


% Matriz de ocurrencias A
A_tipo = {};
for i=1:length(noticias)
    url = noticias{i};
    txt = extraer_texto(url);
    for j=1:length(palabras_tipo_final)        
        A_tipo{i,j} = length(strfind(txt,palabras_tipo_final{j}))
    end
end

% Se guarda la variable A.mat
save A_tipo.mat A_tipo 
 

A_lugar = {};
for i=1:length(noticias_lugar)
    url = noticias_lugar{i};
    txt = extraer_texto(url);
    for j=1:length(palabras_lugar_final)        
        A_lugar{i,j} = length(strfind(txt,palabras_lugar_final{j}))
    end
end

save A_lugar.mat A_lugar 

% Se transforma la variable tipo cell a mat para poder aplicar nnmf
A2 = cell2mat(A_tipo);

% Se obtienen las matrices W y H para definir el tipode noticia
[W2,H2] = nnmf(A2,80);

save W2.mat W2;
save H2.mat H2;

% Se agrega la categoria para poder usar la aplicacion Classification
% Learner
Tipo = cell2table(num2cell(W2));
Tipo.Clase = Categoria_tipo';

% Mismo procedimiento para la clasificacion del lugar
A3 = cell2mat(A_lugar);

[W3,H3] = nnmf(A3,80);

save W3.mat W3;
save H3.mat H3;

Origen = cell2table(num2cell(W3));
Origen.Lugar = Categoria_lugar';

% Al usar la aplicacion Classification Learner se prueban todos los modelos
% SVM y se exporta el que arroja mayor tasa de acierto para cada
% clasificacion. Los clasificadores se guardan para su uso posterior
% (clasificacion de nuevas noticias)
% 
% save trainedClassifier_tipo.mat trainedClassifier_tipo
% save trainedClassifier_lugar.mat trainedClassifier_lugar
%
% las dos lineas superiores estan comentadas porque los clasificadores ya
% estan guardados

%% Funcionamiento 
% el funcionamiento ya esta implementado en la funcion predecir.m
% 
% url = 'http://www.emol.com/noticias/Deportes/2018/06/24/911011/La-U-salva-su-honra-sobre-el-final-y-derrota-con-lo-justo-al-modesto-Colchagua-por-los-octavos-de-Copa-Chile.html';
% txt = extraer_texto(url);
% 
% palabras_encontradas = {};
% for i = 1:length(palabras_tipo_final)
%     palabras_encontradas{i} = length(strfind(txt, palabras_tipo_final{i}));
% end
% mat_palabras = cell2mat(palabras_encontradas);
% Var = max(mat_palabras/H2,0);
% W2_table = array2table(Var);
% 
% trainedClassifier_tipo.predictFcn(W2_table)
% 
% 
% palabras_encontradas2 = {};
% for i = 1:length(palabras_lugar_final)
%     palabras_encontradas2{i} = length(strfind(txt, palabras_lugar_final{i}));
% end
% mat_palabras2 = cell2mat(palabras_encontradas2);
% Var = max(mat_palabras2/H3,0);
% W3_table = array2table(Var);
% 
% trainedClassifier_lugar.predictFcn(W3_table)

